# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-playbook.json
---
- hosts: all
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  vars_prompt:
    - name: user_pw
      prompt: Enter your users password
      unsafe: true
      private: true
      confirm: true
  tasks:
    - include: tasks/osx.yml
      when: ansible_facts['os_family'] == "Darwin"
