---
- name: "Install homebrew packages"
  community.general.homebrew:
    name: [
      # Update common tools
      'python',
      'vim',
      'grep',
      'openssh',
      'bash',  # bash 4
      'bash-completions@2',
      'zsh-completions'
    ]
# - name: Determine Homebrew ownership variables
#   set_fact:
#     homebrew_user: '{{ homebrew_user | default(ansible_user_id) }}'
#     homebrew_group: '{{ homebrew_group | default(ansible_user_gid) }}'
# https://github.com/geerlingguy/ansible-collection-mac/blob/8b4c9db2c655c3fe9d238ceaad353652572057f2/roles/homebrew/tasks/main.yml
# - name: Ensure Homebrew parent directory has correct permissions (M1).
#   file:
#     path: "{{ homebrew_prefix }}/"
#     owner: "{{ homebrew_user }}"
#     state: directory
#     mode: '0775'
#     recurse: true
#   become: true
#   become_method: sudo
#   when: ansible_machine == 'arm64'

# - name: Ensure Homebrew parent directory has correct permissions (Intel).
#   block:
#     - name: Ensure Homebrew parent directory has correct permissions (MacOS >= 10.13).
#       file:
#         path: "{{ homebrew_prefix }}/"
#         owner: root
#         state: directory
#         mode: '0775'
#         recurse: true
#       become: true
#       become_method: sudo
#       when: "ansible_distribution_version is version('10.13', '>=')"

#     - name: Ensure Homebrew parent directory has correct permissions (MacOS < 10.13).
#       file:
#         path: "{{ homebrew_prefix }}/"
#         owner: root
#         group: admin
#         state: directory
#         mode: '0775'
#         recurse: true
#       become: true
#       become_method: sudo
#       when: "ansible_distribution_version is version('10.13', '<')"
#   when: ansible_machine == 'x86_64'
# - name: Download Homebrew installation script
#   get_url:
#     url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
#     dest: /tmp/installbrew
# - name: Install Homebrew
#   become: false
#   ansible.builtin.expect:
#     command: /bin/bash /tmp/installbrew
#     responses:
#       (?i)password: "{{ user_pw }}"
#       Press(.*)RETURN(.*)to continue: ""
