---
- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory
  tags:
    - install
    - ssh
- name: Generate an Open SSH key pair
  community.crypto.openssh_keypair:
    path: "{{ lookup('env','HOME') }}/.ssh/id_ed25519"
    type: ed25519
    comment: "{{ ds_email }}"

- name: Read SSH public key to authorize
  ansible.builtin.command: cat /home/foo/.ssh/id_ed25519.pub
  register: ssh_pub_key
  changed_when: ssh_pub_key.rc != 0

- name: Authorize key with GitHub
  local_action:  # noqa deprecated-local-action
    module: github_key
    name: Access Key for {{ machine_hostname }}
    token: '{{ github_access_token }}'
    pubkey: '{{ ssh_pub_key.stdout }}'
