---
- name: add local domain
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: local-web.dev.datasite.com"
    line: '127.0.0.1   local-web.dev.datasite.com'
    state: present
    backup: true
    validate: cat /etc/hosts | grep 'local-web.dev.datasite.com'
  become: true
  tags:
    - sudoers
    - config
