---
- name: add local domain
  ansible.builtin.lineinfile: >
    dest=/etc/hosts regexp="local-web.dev.datasite.com$" line='{{ item }}'
    state=present backup=yes backrefs=yes
  with_items:
  - '127.0.0.1    local-web.dev.datasite.com'
  tags:
  - sudoers
  - config
