name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          ignore_paths: >-
            test/test_helper/bats-assert
            test/test_helper/bats-support

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15]
        # Ready for future expansion with:
        # os: [macos-15, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup Bats and bats libs
      id: setup-bats
      uses: bats-core/bats-action@3.0.0
      with:
        bats-version: 1.11.1 
    - name: bats
      shell: bash
      env:
        BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        TERM: xterm
      run: bats test
