name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Setup Bats and bats libs
      id: setup-bats
      uses: bats-core/bats-action@3.0.0
      with:
        bats-version: 1.11.1 
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
    - name: Test
      shell: bash
      env:
        BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
        TERM: xterm
      run: bats test
